package main

import (
	"fmt"
	"html/template"
	"log"
	"os"
)

// simple template to generate function
// berdasarkan input
const templateText = `
// Code generated by xyz. DO NOT EDIT.

package main

import "fmt"

func main(){
	// call functions
	{{range . -}}
	{{.FunctionName}}()
	{{end}}
}

{{range .}}

func {{.FunctionName}}(){
	fmt.Println("Halo dunia dari function {{.FunctionName}}()")
}

{{end}}
`

type FuncList struct {
	FunctionName string
}

// main function
func main() {
	stds := []FuncList{{FunctionName: "helloWorld"}, {FunctionName: "haloDunia"}}

	// "New" membuat template baru
	// dengan nama Template_5
	tmp1 := template.New("Template_5")

	tmp1, err := tmp1.Parse(templateText)
	if err != nil {
		log.Fatalf("parsing: %s", err)
	}
	// standard output untuk menampilkan
	// string beserta value dari struct
	if err := tmp1.Execute(os.Stdout, stds); err != nil {
		// print error jika ada
		fmt.Println(err)
	}
}
