version : "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name : km-prometheus
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
    - "9090:9090"
    volumes:
    - $PWD/prom-config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise
    container_name : km-grafana
    ports:
    - "3000:3000"

