baseURL = "https://damarasf.github.io/playground/"
languageCode = "id"
title = "Site Hugo Baru"
paginate = 10
theme = "hulga"

[params]
subtitle = "Keterangan website."
copyright = "Copyright © 2021"

[menu]
[[menu.main]]
identifier = "index"
name = "index"
url = "/"
weight = 1

[taxonomies]
category = "categories"
tag = "tags"