name: Golang Unit Test
on:
  pull_request:
    paths:
      - "backend/**"

jobs:
  run:
    name: Unit Test
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.1' 
      - run: go mod tidy
      - run: go install golang.org/x/tools/cmd/benchcmp@latest
      - run: go test -v ./...
